class Book {
  String cover, title, author, status, date, clientName;

  Book({
    this.cover,
    this.title,
    this.author,
    this.status,
    this.date,
    this.clientName,
  });
}

List<Book> books = [
  Book(
    title: '1984',
    author: 'George Orwell',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/1984.jpg',
    clientName: '0',
  ),
  Book(
    title: 'A Revolução dos Bichos',
    author: 'George Orwell',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/a-revolucao-dos-bichos.jpg',
    clientName: '0',
  ),
  Book(
    title: 'Jogos Vorazes',
    author: 'Suzanne Collins',
    status: 'Indisponível',
    date: '11/05/2021',
    cover: 'assets/images/jogos-vorazes.jpg',
    clientName: 'Pedro Henrique',
  ),
  Book(
    title: 'Em Chamas',
    author: 'Suzanne Collins',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/em-chamas.jpg',
    clientName: '0',
  ),
  Book(
    title: 'A Esperança',
    author: 'Suzanne Collins',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/a-esperanca.jpg',
    clientName: '0',
  ),
  Book(
    title: 'Harry Potter e a Pedra Filosofal',
    author: 'J.K. Rowling',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/hp-e-a-pedra-filosofal.jpg',
    clientName: '0',
  ),
  Book(
    title: 'Harry Potter e a Câmara Secreta',
    author: 'J.K. Rowling',
    status: 'Indisponível',
    date: '08/05/2021',
    cover: 'assets/images/hp-e-a-camara-secreta.jpg',
    clientName: 'Renato Gomes',
  ),
  Book(
    title: 'Harry Potter e o Cálice de Fogo',
    author: 'J.K. Rowling',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/hp-e-o-calice-de-fogo.jpg',
    clientName: '0',
  ),
  Book(
    title: 'Harry Potter e o Prisioneiro de Azkaban',
    author: 'J.K. Rowling',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/hp-e-o-prisioneiro-de-azkaban.jpg',
    clientName: '0',
  ),
  Book(
    title: 'O Mágico de Oz',
    author: 'L. Frank Baum',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/o-magico-de-oz.jpg',
    clientName: '0',
  ),
  Book(
    title: 'O Pequeno Príncipe',
    author: 'Antoine De Saint-exupéry',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/o-pequeno-principe.jpg',
    clientName: '0',
  ),
  Book(
    title: 'O Que o Sol Faz Com as Flores',
    author: 'Rupi Kaur',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/o-que-o-sol-faz-com-as-flores.jpg',
    clientName: '0',
  ),
  Book(
    title: 'Outros Jeitos de Usar a Boca',
    author: 'Rupi Kaur',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/outros-jeitos-de-usar-a-boca.jpg',
    clientName: '0',
  ),
  Book(
    title: 'A Menina Que Roubava Livros',
    author: 'Markus Zusak',
    status: 'Disponível',
    date: '0',
    cover: 'assets/images/a-menina-que-roubava-livros.jpg',
    clientName: '0',
  ),
];
